[postgres]
# use_local = true: Die lokale Website nutzt die lokale Datei (dart_data.db) für Tests.
# Auf Streamlit Cloud greift die Online-Website weiterhin direkt auf Supabase zu!
use_local = true
url = "postgresql://postgres.tqajpkonwdmnuzgqsyvn:Luca03091510%21@aws-0-eu-central-1.pooler.supabase.com:5432/postgres"

